version: '2'
services:
    rsdata-app:
        image: rsdata
        external_links:
            - rsdata-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/rsdata?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rsdata-mysql:
        extends:
            file: mysql.yml
            service: rsdata-mysql
